# Generated by Django 3.2.4 on 2021-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210616_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_version',
            field=models.CharField(default='x', max_length=50, verbose_name='text'),
        ),
    ]
