# Generated by Django 3.2.4 on 2021-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_url_short_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_version',
            field=models.CharField(default='x', max_length=50, verbose_name='short_version'),
        ),
    ]
