# Generated by Django 3.2.4 on 2021-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_url_short_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='text',
            field=models.CharField(default='x', max_length=50, verbose_name='text'),
        ),
    ]
